DROP TABLE IF EXISTS memos;

CREATE TABLE memos (
    ID SERIAL PRIMARY KEY,
    UserID VARCHAR(255) NOT NULL,
    ArticleURL TEXT NOT NULL,
    Content TEXT NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);